### ISSUE TITLE
Error on tests

### ISSUE THREAD

**Issue by luccasklotz** [intuit/fuzzy-matcher#14] opened 2019-09-03 20:28 UTC
Hi !

I am getting this error when trying to install

`Tests run: 81, Failures: 0, Errors: 8, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.490 s
[INFO] Finished at: 2019-09-03T17:25:48-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project fuzzy-matcher: There are test failures.
[ERROR]
[ERROR] Please refer to c:\Users\Luccas Klotz\Downloads\fuzzy-matcher-master\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

If I go to the \fuzzy-matcher-master\target\surefire-reports, errors are in the tests where files such as demo.csv and test-data.csv could not be found, but the files are there.

Any clues?

Thanks !

**Comment by manishobhatia** [comment] 2019-09-03 21:53
Hi Lucas,

Can you share the exceptions from the test failures ? 

If all the files are downloaded properly the only other thing I can suspect is the eol (end of line) difference between a unix and windows. It could be possible when doing a git clone these files were not formatted correctly for a windows system.

If I can see the exception with any one of the tests, will get a better idea on what the issue is.

Also note that the latest build is published to maven central, you could use this dependency into your project without having to build / install locally
```
<dependency>
    <groupId>com.intuit.fuzzymatcher</groupId>
    <artifactId>fuzzy-matcher</artifactId>
    <version>0.4.2</version>
</dependency>
```

**Comment by manishobhatia** [comment] 2019-09-10 18:33
Closing issue, feel free to open another issue if you believe its not resolved , or have further details on the issue

**Closed by manishobhatia** 2019-09-10 18:33 UTC
